---
name: Docker

"on":
  push:
    branches: [master]
  pull_request:
    branches: [master]
  release:
    types: [published]

env:
  IMAGE_NAME: kornicameister/gh-secrets-action
  DOCKER_BUILDKIT: 1

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: brpaz/hadolint-action@v1.3.1
  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2
      - name: Check build
        if: github.event_name == 'pull_request'
        env:
          IMAGE_VERSION_NEXT: $(date +%s)
        run: |
          docker build \
            --tag ${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION_NEXT }} \
            .
      - name: Build & Publish latest
        if: github.event_name == 'push'
        uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ env.IMAGE_NAME }}
          tags: latest
          tag_with_sha: true
  release:
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    steps:
      - uses: actions/checkout@v2
      - name: Build & Publish latest
        uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ env.IMAGE_NAME }}
          tag_with_ref: true
          push: ${{ startsWith(github.ref, 'refs/tags/') }}
