---
name: Docker

"on":
  push:
    branches: [master]
  pull_request:
    branches: [master]
  release:
    types: [published]

env:
  IMAGE_NAME: kornicameister/gh-secrets-action
  DOCKER_BUILDKIT: 1

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: brpaz/hadolint-action@v1.0.2
  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2
      - name: Check build
        if: github.event_name == 'pull_request'
        env:
          IMAGE_VERSION_NEXT: $(date +%s)
        run: |
          docker build \
            --tag ${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION_NEXT }} \
            .
      - name: Build & Publish latest
        uses: elgohr/Publish-Docker-Github-Action@2.13
        if: github.event_name == 'push'
        with:
          name: ${{ env.IMAGE_NAME }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          snapshot: true
          tags: "latest"
  release:
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    steps:
      - uses: actions/checkout@v2
      - name: Pull latest
        run: |
          docker pull ${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION_LATEST }}
      - name: Build & Publish release
        if: github.event_name == 'push'
        uses: elgohr/Publish-Docker-Github-Action@2.13
        with:
          name: ${{ env.IMAGE_NAME }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tag_semver: true
