---
name: Python

"on":
  push:
    branches: [master]
  pull_request:

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt -r test-requirements.txt
        working-directory: python/
      - name: Lint
        run: |
          pip check
          flake8 ghsa/
          mypy -p ghsa
          black --check ghsa/
          safety check -r requirements.txt
        working-directory: python/
